// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: control.proto

package grpcctl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_Metrics
	//	*WorkerMessage_Ack
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetMetrics() *MetricsReport {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *WorkerMessage) GetAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_Metrics struct {
	Metrics *MetricsReport `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"`
}

type WorkerMessage_Ack struct {
	Ack *CommandAck `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Payload() {}

func (*WorkerMessage_Metrics) isWorkerMessage_Payload() {}

func (*WorkerMessage_Ack) isWorkerMessage_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TsUnix        int64                  `protobuf:"varint,2,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *Heartbeat) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type MetricsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           float64                `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryMb      float64                `protobuf:"fixed64,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	PagesPerMin   float64                `protobuf:"fixed64,3,opt,name=pages_per_min,json=pagesPerMin,proto3" json:"pages_per_min,omitempty"`
	FailRate      float64                `protobuf:"fixed64,4,opt,name=fail_rate,json=failRate,proto3" json:"fail_rate,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsReport) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *MetricsReport) GetMemoryMb() float64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *MetricsReport) GetPagesPerMin() float64 {
	if x != nil {
		return x.PagesPerMin
	}
	return 0
}

func (x *MetricsReport) GetFailRate() float64 {
	if x != nil {
		return x.FailRate
	}
	return 0
}

func (x *MetricsReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MasterCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MasterCommand_RateLimit
	//	*MasterCommand_RuleReload
	//	*MasterCommand_Shutdown
	Payload       isMasterCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterCommand) Reset() {
	*x = MasterCommand{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterCommand) ProtoMessage() {}

func (x *MasterCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterCommand.ProtoReflect.Descriptor instead.
func (*MasterCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *MasterCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *MasterCommand) GetPayload() isMasterCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MasterCommand) GetRateLimit() *RateLimitCmd {
	if x != nil {
		if x, ok := x.Payload.(*MasterCommand_RateLimit); ok {
			return x.RateLimit
		}
	}
	return nil
}

func (x *MasterCommand) GetRuleReload() *RuleHotReload {
	if x != nil {
		if x, ok := x.Payload.(*MasterCommand_RuleReload); ok {
			return x.RuleReload
		}
	}
	return nil
}

func (x *MasterCommand) GetShutdown() *ShutdownCmd {
	if x != nil {
		if x, ok := x.Payload.(*MasterCommand_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isMasterCommand_Payload interface {
	isMasterCommand_Payload()
}

type MasterCommand_RateLimit struct {
	RateLimit *RateLimitCmd `protobuf:"bytes,2,opt,name=rate_limit,json=rateLimit,proto3,oneof"`
}

type MasterCommand_RuleReload struct {
	RuleReload *RuleHotReload `protobuf:"bytes,3,opt,name=rule_reload,json=ruleReload,proto3,oneof"`
}

type MasterCommand_Shutdown struct {
	Shutdown *ShutdownCmd `protobuf:"bytes,4,opt,name=shutdown,proto3,oneof"`
}

func (*MasterCommand_RateLimit) isMasterCommand_Payload() {}

func (*MasterCommand_RuleReload) isMasterCommand_Payload() {}

func (*MasterCommand_Shutdown) isMasterCommand_Payload() {}

type RateLimitCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Qps           float64                `protobuf:"fixed64,2,opt,name=qps,proto3" json:"qps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitCmd) Reset() {
	*x = RateLimitCmd{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitCmd) ProtoMessage() {}

func (x *RateLimitCmd) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitCmd.ProtoReflect.Descriptor instead.
func (*RateLimitCmd) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *RateLimitCmd) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RateLimitCmd) GetQps() float64 {
	if x != nil {
		return x.Qps
	}
	return 0
}

type RuleHotReload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int64                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleHotReload) Reset() {
	*x = RuleHotReload{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleHotReload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleHotReload) ProtoMessage() {}

func (x *RuleHotReload) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleHotReload.ProtoReflect.Descriptor instead.
func (*RuleHotReload) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *RuleHotReload) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *RuleHotReload) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ShutdownCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	GraceSeconds  int32                  `protobuf:"varint,2,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownCmd) Reset() {
	*x = ShutdownCmd{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownCmd) ProtoMessage() {}

func (x *ShutdownCmd) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownCmd.ProtoReflect.Descriptor instead.
func (*ShutdownCmd) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *ShutdownCmd) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ShutdownCmd) GetGraceSeconds() int32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\acontrol\"\xc8\x01\n" +
	"\rWorkerMessage\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x122\n" +
	"\theartbeat\x18\x02 \x01(\v2\x12.control.HeartbeatH\x00R\theartbeat\x122\n" +
	"\ametrics\x18\x03 \x01(\v2\x16.control.MetricsReportH\x00R\ametrics\x12'\n" +
	"\x03ack\x18\x04 \x01(\v2\x13.control.CommandAckH\x00R\x03ackB\t\n" +
	"\apayload\"P\n" +
	"\tHeartbeat\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\ats_unix\x18\x02 \x01(\x03R\x06tsUnix\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\x97\x01\n" +
	"\rMetricsReport\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x01R\x03cpu\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x01R\bmemoryMb\x12\"\n" +
	"\rpages_per_min\x18\x03 \x01(\x01R\vpagesPerMin\x12\x1b\n" +
	"\tfail_rate\x18\x04 \x01(\x01R\bfailRate\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"Q\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xe0\x01\n" +
	"\rMasterCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x126\n" +
	"\n" +
	"rate_limit\x18\x02 \x01(\v2\x15.control.RateLimitCmdH\x00R\trateLimit\x129\n" +
	"\vrule_reload\x18\x03 \x01(\v2\x16.control.RuleHotReloadH\x00R\n" +
	"ruleReload\x122\n" +
	"\bshutdown\x18\x04 \x01(\v2\x14.control.ShutdownCmdH\x00R\bshutdownB\t\n" +
	"\apayload\"8\n" +
	"\fRateLimitCmd\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x10\n" +
	"\x03qps\x18\x02 \x01(\x01R\x03qps\"B\n" +
	"\rRuleHotReload\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x03R\x06ruleId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"J\n" +
	"\vShutdownCmd\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12#\n" +
	"\rgrace_seconds\x18\x02 \x01(\x05R\fgraceSeconds2M\n" +
	"\fControlPlane\x12=\n" +
	"\aConnect\x12\x16.control.WorkerMessage\x1a\x16.control.MasterCommand(\x010\x01B#Z!goscrapy/internal/grpcctl;grpcctlb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_control_proto_goTypes = []any{
	(*WorkerMessage)(nil), // 0: control.WorkerMessage
	(*Heartbeat)(nil),     // 1: control.Heartbeat
	(*MetricsReport)(nil), // 2: control.MetricsReport
	(*CommandAck)(nil),    // 3: control.CommandAck
	(*MasterCommand)(nil), // 4: control.MasterCommand
	(*RateLimitCmd)(nil),  // 5: control.RateLimitCmd
	(*RuleHotReload)(nil), // 6: control.RuleHotReload
	(*ShutdownCmd)(nil),   // 7: control.ShutdownCmd
}
var file_control_proto_depIdxs = []int32{
	1, // 0: control.WorkerMessage.heartbeat:type_name -> control.Heartbeat
	2, // 1: control.WorkerMessage.metrics:type_name -> control.MetricsReport
	3, // 2: control.WorkerMessage.ack:type_name -> control.CommandAck
	5, // 3: control.MasterCommand.rate_limit:type_name -> control.RateLimitCmd
	6, // 4: control.MasterCommand.rule_reload:type_name -> control.RuleHotReload
	7, // 5: control.MasterCommand.shutdown:type_name -> control.ShutdownCmd
	0, // 6: control.ControlPlane.Connect:input_type -> control.WorkerMessage
	4, // 7: control.ControlPlane.Connect:output_type -> control.MasterCommand
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_Metrics)(nil),
		(*WorkerMessage_Ack)(nil),
	}
	file_control_proto_msgTypes[4].OneofWrappers = []any{
		(*MasterCommand_RateLimit)(nil),
		(*MasterCommand_RuleReload)(nil),
		(*MasterCommand_Shutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
